# Generated by Django 2.0.4 on 2018-06-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20180617_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
