# Generated by Django 2.0.4 on 2018-06-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20180617_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(max_length=1500),
        ),
    ]
