# Generated by Django 2.0.4 on 2018-06-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_thread_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='votes',
        ),
    ]
