# Generated by Django 2.0.4 on 2018-06-18 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0008_auto_20180618_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='thread',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='vote_score',
        ),
        migrations.AddField(
            model_name='threadvotes',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.Thread'),
        ),
        migrations.AddField(
            model_name='threadvotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
