# Generated by Django 2.0.4 on 2018-06-18 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0009_auto_20180618_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='votes',
            field=models.ManyToManyField(related_name='thread_votes', through='threads.ThreadVotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
