# Generated by Django 2.0.4 on 2018-06-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0010_thread_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadvotes',
            name='vote_action',
            field=models.BooleanField(default=False),
        ),
    ]
