# Generated by Django 2.0.4 on 2018-07-04 21:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0011_threadvotes_vote_action'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='threadvotes',
            unique_together={('user', 'thread')},
        ),
    ]
