# Generated by Django 2.0.4 on 2018-06-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_comment_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentvotes',
            name='vote_action',
            field=models.BooleanField(default=False),
        ),
    ]
