# Generated by Django 2.0.4 on 2018-07-04 21:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0009_commentvotes_vote_action'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvotes',
            unique_together={('user', 'comment')},
        ),
    ]
