# Generated by Django 2.0.4 on 2018-07-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_channel_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='icon',
            field=models.CharField(blank=True, max_length=32768),
        ),
    ]
