# Generated by Django 2.0.4 on 2018-07-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_channel_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='icon',
            field=models.CharField(blank=True, max_length=65536),
        ),
    ]
