# Generated by Django 2.0.4 on 2018-05-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '__first__'),
        ('users', '0002_auto_20171227_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_channels',
            field=models.ManyToManyField(to='channels.Channel'),
        ),
    ]
