# Generated by Django 2.0.4 on 2018-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '__first__'),
        ('users', '0003_user_subscribed_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_threads',
            field=models.ManyToManyField(to='threads.Thread'),
        ),
    ]
